### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by E-daw** [ichttt/Eternal-Winter#1]
So in the config file "Eternal Winter.cfg" when I set oceans and rivers freezing to true they don't end up freezing over. Any ice you already see is apart of the beaches of the biome.
![2017-11-26_19 31 37](https://user-images.githubusercontent.com/34014927/33247047-b94f7cec-d2e0-11e7-9d35-7a63078ad184.png)
![2017-11-26_19 31 34](https://user-images.githubusercontent.com/34014927/33247048-ba6dead2-d2e0-11e7-8b10-4cbbd1de2c47.png)
![picture of thing](https://user-images.githubusercontent.com/34014927/33247057-c880723e-d2e0-11e7-867e-9f2622ece27d.png)

**Comment by ichttt** [comment]
If you set the config after the terrain has been generated, it will freeze when it starts to snow, but it will take a while. There was also a bug where the config did not save when editing it in the GUI, but thats fixed in the next version as well
