### ISSUE TITLE
Snow not appearing.

### ISSUE THREAD

**Issue by Suomia** [ichttt/Eternal-Winter#5]
Good day, I hope whoever is reading this is having a good time.

I'm using the 1.12.2 version of Minecraft, after I installed the mod and crated a new world, the snow refuses to appear. This issue has been going like this since january of this year and I haven't found a way to make the snow appear on all biomes, and I wonder if it's thanks to a Minecraft Update or something.

If there's anything I could do to fix the mod issue, please, let me know.

**Comment by ichttt** [comment]
The terrain only has snow when a) the chunk is newly generated while the mod is installed or b) it is currently snowing onto the block.
I think this is likely your issue.

**Comment by Suomia** [comment]
You might not believe it, but it seems that my issue has fixed itself by clicking on the mod and resetting it to Default, the snow is finally here.

Thank you very much for your reply, though!

**Comment by ichttt** [comment]
Oh well, weird but fixed is fixed :D
